from tkinter import *
root=Tk()
topframe=Frame(root)
topframe.pack()
bottomframe=Frame(root)
bottomframe.pack(side=BOTTOM)
b1=Button(topframe,text="Button 1",fg="red")
b2=Button(topframe,text="Button 2",fg="blue")
b3=Button(topframe,text="Button 3",fg="green")
b4=Button(bottomframe,text="Button 4",fg="tomato")
b1.pack(side=RIGHT)
b2.pack(side=RIGHT)
b3.pack(side=RIGHT)
b4.pack()
root.mainloop()